title: "Banana Bit"
author: "Norah Alsunaidi"
description: "Casual CS-related content.  This blog is the aftermath of questioning the nature of things then overthinking about it... this is thinking out loud backed with reference  " # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "example@mail.com"
#twitter_username: "twitteruser"
github_username: "NorahTheGreat"
linkedin_username: "norah-alsunaidi"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
